### ISSUE TITLE
The data_loader problem about npy

### ISSUE THREAD

**Issue by dengxiongshi** [megvii-research/LBHomo#11]
I downloaded the datasets and unzip it. When I to debug the evaluate.py, I can't find the points_path in HomoTestData, just like 00000100_10011_00000100_10032.npy.
![image](https://github.com/user-attachments/assets/763ec5e4-7622-486c-84bd-1904818980c5)

**Comment by lhaippp** [comment]
Is it a general issue (which means none of the test case you can find)? 

if not, try to remove this pth (i.e., 00000100_10011_00000100_10032.npy)

**Comment by dengxiongshi** [comment]
@lhaippp Hello, it is not a general issue, I found is a dataset issue. I have redownloaded datasets from [Deep Homography](https://github.com/JirongZhang/DeepHomography) and unzip it from Data/Coordinate-v2/Corrdinate. I used the Test_list.txt to test, the following is my change:
![image](https://github.com/user-attachments/assets/e467279d-0e18-4529-98c9-2ece5aca5e55)
